# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: smbCloudXYZ.smbcloud-cli
PackageVersion: 0.6.1
InstallerType: portable
Commands:
- smb
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/smbcloudXYZ/smbcloud-cli/releases/download/v0.6.1/smb-win-amd64.exe
  InstallerSha256: 01DD21AE05569EBE5666148C69ADC5F09FA6C17AA02C278861FEA82B58A8F2D1
- Architecture: arm64
  InstallerUrl: https://github.com/smbcloudXYZ/smbcloud-cli/releases/download/v0.6.1/smb-win-arm64.exe
  InstallerSha256: 0B6B646F6B796B1874B1DF36EF9402191CF58FCBCF895325CD6DE936E887DC78
ManifestType: installer
ManifestVersion: 1.6.0
ReleaseDate: 2026-10-04
