# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: smbCloudXYZ.smbcloud-cli
PackageVersion: 0.6.2
InstallerType: portable
Commands:
- smb
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/smbcloudXYZ/smbcloud-cli/releases/download/v0.6.2/smb-win-amd64.exe
  InstallerSha256: C0D265FF20D33CC0A2DEE21446CC21227C42D1A64FF5077392B429111AD345BE
- Architecture: arm64
  InstallerUrl: https://github.com/smbcloudXYZ/smbcloud-cli/releases/download/v0.6.2/smb-win-arm64.exe
  InstallerSha256: 65A872672568F219EBC6AC1978D8F2E5DC08CCE42F577AED91D00E9FEA051B3E
ManifestType: installer
ManifestVersion: 1.6.0
ReleaseDate: 2026-10-04
