# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: smbCloudXYZ.smbcloud-cli
PackageVersion: 0.7.0
InstallerType: portable
Commands:
- smb
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/smbcloudXYZ/smbcloud-cli/releases/download/v0.7.0/smb-win-amd64.exe
  InstallerSha256: 57BFA3F39B8C4288E6F7A18EC6C798A7AEFA6A3EDA7A72FDCB9564542B378365
- Architecture: arm64
  InstallerUrl: https://github.com/smbcloudXYZ/smbcloud-cli/releases/download/v0.7.0/smb-win-arm64.exe
  InstallerSha256: BB321EF7F13EF8B2A6845932FA79CE81AB27E5581149045DCBB88C0B87FFBE96
ManifestType: installer
ManifestVersion: 1.6.0
ReleaseDate: 2026-10-06
